# Generated by Django 3.1.5 on 2021-02-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='secondGenre',
            field=models.CharField(default='AC', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorites',
            name='thirdGenre',
            field=models.CharField(default='AC', max_length=50),
            preserve_default=False,
        ),
    ]
