# Generated by Django 3.1.5 on 2021-02-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210203_0446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
