# Generated by Django 3.1.5 on 2021-02-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210212_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='core.Genre'),
        ),
    ]
