# Generated by Django 3.1.5 on 2021-02-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210213_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='api_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='user_added',
            field=models.BooleanField(default=False),
        ),
    ]
