# Generated by Django 3.1.5 on 2021-03-04 01:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210213_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 4, 1, 22, 31, 65462, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
