# Generated by Django 3.1.5 on 2021-03-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210307_0839'),
        ('core', '0016_review_added'),
    ]

    operations = [
    ]
