# Generated by Django 3.1.5 on 2021-03-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20210313_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/person_icon.png', null=True, upload_to='users/'),
        ),
    ]
