# Generated by Django 3.1.5 on 2021-03-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20210314_1635'),
        ('core', '0018_merge_20210312_0137'),
        ('core', '0019_auto_20210313_0451'),
    ]

    operations = [
    ]
