# Generated by Django 3.1.5 on 2021-03-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20210320_1858'),
        ('core', '0020_merge_20210315_1522'),
    ]

    operations = [
    ]
