# Generated by Django 3.1.5 on 2021-03-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20210328_1658'),
        ('core', '0021_merge_20210328_2251'),
        ('core', '0020_merge_20210317_1530'),
        ('core', '0020_merge_20210315_2037'),
    ]

    operations = [
    ]
