# Generated by Django 3.1.5 on 2021-04-17 05:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210410_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='UserBio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
