# Generated by Django 3.1.5 on 2021-04-17 05:48

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_userprofile_userbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='UserBio',
            field=models.CharField(blank=True, default='This is your bio.', max_length=150, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
