# Generated by Django 3.1.5 on 2021-04-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210417_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='UserBio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_bio',
            field=models.CharField(blank=True, default='This is your bio.', max_length=150, null=True),
        ),
    ]
