# Generated by Django 3.1.5 on 2021-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210418_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isPrivate',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
